// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXLAgW9QPkVzlWin7F6We2dBzasx71r4U',
    appId: '1:437989116022:web:525a48868980f93413b757',
    messagingSenderId: '437989116022',
    projectId: 'just-some-notes',
    authDomain: 'just-some-notes.firebaseapp.com',
    storageBucket: 'just-some-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkYw57KXbsnp9DKzeZF6EIh01jtD_SpuA',
    appId: '1:437989116022:android:c2b3a26725d84dc313b757',
    messagingSenderId: '437989116022',
    projectId: 'just-some-notes',
    storageBucket: 'just-some-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL7jImfdxWgmyPGlRb38pOc-yo3DIwRUs',
    appId: '1:437989116022:ios:9c5e1d24ccf0272813b757',
    messagingSenderId: '437989116022',
    projectId: 'just-some-notes',
    storageBucket: 'just-some-notes.appspot.com',
    iosClientId: '437989116022-1igp7i233qpjduicqukd37n5gufh28e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.dart',
  );
}
